name: Build CLI App with Dockerfile

on:
    pull_request:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
      
    - name: Build Docker Image
      run: docker build -t bankid .

    - name: Log in to GitHub Packages
      run: docker login docker.pkg.github.com -u ${{secrets.CONTAINER_USERNAME}} --password-stdin

    - name: Push Docker Image
      env:
        TAG: latest
      run: |
            docker tag bankid docker.pkg.github.com/nicolaa5/bankid/cli:TAG
            docker push docker.pkg.github.com/nicolaa5/bankid/cli:TAG