name: Unit Tests
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  unit-tests:
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go 1.21.0
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: run unit tests
        run: go test .